//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Wcf.TenantDbService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemCode", Namespace="http://schemas.datacontract.org/2004/07/aZaaS.Workflow.WcfService")]
    public enum SystemCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AzaasEngineServer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KStarFramework = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KStarService = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KStarWorkSpace = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AzaasUM = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AzaasWorkSpace = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TenantDbService.ITenantDatabaseService")]
    public interface ITenantDatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantDatabaseService/GetConnectionString", ReplyAction="http://tempuri.org/ITenantDatabaseService/GetConnectionStringResponse")]
        string GetConnectionString(string tenantID, aZaaS.KStar.Wcf.TenantDbService.SystemCode systemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantDatabaseService/GetConnectionString", ReplyAction="http://tempuri.org/ITenantDatabaseService/GetConnectionStringResponse")]
        System.Threading.Tasks.Task<string> GetConnectionStringAsync(string tenantID, aZaaS.KStar.Wcf.TenantDbService.SystemCode systemCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITenantDatabaseServiceChannel : aZaaS.KStar.Wcf.TenantDbService.ITenantDatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TenantDatabaseServiceClient : System.ServiceModel.ClientBase<aZaaS.KStar.Wcf.TenantDbService.ITenantDatabaseService>, aZaaS.KStar.Wcf.TenantDbService.ITenantDatabaseService {
        
        public TenantDatabaseServiceClient() {
        }
        
        public TenantDatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TenantDatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenantDatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenantDatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetConnectionString(string tenantID, aZaaS.KStar.Wcf.TenantDbService.SystemCode systemCode) {
            return base.Channel.GetConnectionString(tenantID, systemCode);
        }
        
        public System.Threading.Tasks.Task<string> GetConnectionStringAsync(string tenantID, aZaaS.KStar.Wcf.TenantDbService.SystemCode systemCode) {
            return base.Channel.GetConnectionStringAsync(tenantID, systemCode);
        }
    }
}
