//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.CallCoreMailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CallCoreMailService.ICallCoreMail")]
    public interface ICallCoreMail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCoreMail/SendMail", ReplyAction="http://tempuri.org/ICallCoreMail/SendMailResponse")]
        int SendMail(string formMail, string ToMail, string Subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCoreMail/SendMail", ReplyAction="http://tempuri.org/ICallCoreMail/SendMailResponse")]
        System.Threading.Tasks.Task<int> SendMailAsync(string formMail, string ToMail, string Subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCoreMail/UserLogin", ReplyAction="http://tempuri.org/ICallCoreMail/UserLoginResponse")]
        string UserLogin(string MailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCoreMail/UserLogin", ReplyAction="http://tempuri.org/ICallCoreMail/UserLoginResponse")]
        System.Threading.Tasks.Task<string> UserLoginAsync(string MailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCoreMail/GetNewListMail", ReplyAction="http://tempuri.org/ICallCoreMail/GetNewListMailResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetNewListMail(string MailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCoreMail/GetNewListMail", ReplyAction="http://tempuri.org/ICallCoreMail/GetNewListMailResponse")]
        System.Threading.Tasks.Task<object[]> GetNewListMailAsync(string MailAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICallCoreMailChannel : aZaaS.KStar.Web.CallCoreMailService.ICallCoreMail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallCoreMailClient : System.ServiceModel.ClientBase<aZaaS.KStar.Web.CallCoreMailService.ICallCoreMail>, aZaaS.KStar.Web.CallCoreMailService.ICallCoreMail {
        
        public CallCoreMailClient() {
        }
        
        public CallCoreMailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallCoreMailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallCoreMailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallCoreMailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SendMail(string formMail, string ToMail, string Subject, string body) {
            return base.Channel.SendMail(formMail, ToMail, Subject, body);
        }
        
        public System.Threading.Tasks.Task<int> SendMailAsync(string formMail, string ToMail, string Subject, string body) {
            return base.Channel.SendMailAsync(formMail, ToMail, Subject, body);
        }
        
        public string UserLogin(string MailAddress) {
            return base.Channel.UserLogin(MailAddress);
        }
        
        public System.Threading.Tasks.Task<string> UserLoginAsync(string MailAddress) {
            return base.Channel.UserLoginAsync(MailAddress);
        }
        
        public object[] GetNewListMail(string MailAddress) {
            return base.Channel.GetNewListMail(MailAddress);
        }
        
        public System.Threading.Tasks.Task<object[]> GetNewListMailAsync(string MailAddress) {
            return base.Channel.GetNewListMailAsync(MailAddress);
        }
    }
}
