//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.ProcessForm
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class ProcessPrognosis
    {
        [Key]
        public System.Guid SysID { get; set; }
        [Required]
        public int ActID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string SourceName { get; set; }
        [Required]
        public string LineName { get; set; }
        [Required]
        public int LinkOrder { get; set; }
        [Required]
        public int ProcInstID { get; set; }
    }
}
