//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOLoginWeb.Manage.DbContext.EntityObject
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public  class RoleUser
    {
        [Key]
        [Column(Order = 0)] 
        public System.Guid Role_SysId { get; set; }
        [Key]
        [Column(Order = 1)] 
        public System.Guid User_SysId { get; set; }
    }
}
