//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BasisEntityContainer : DbContext
    {
        public BasisEntityContainer()
            : base("name=BasisEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Custom_BaseData_ProcessingVendor> Custom_BaseData_ProcessingVendor { get; set; }
        public virtual DbSet<Custom_BaseData_Customer> Custom_BaseData_Customer { get; set; }
        public virtual DbSet<Custom_BaseData_labelTemplate> Custom_BaseData_labelTemplate { get; set; }
        public virtual DbSet<Custom_BaseData_ToolSoft> Custom_BaseData_ToolSoft { get; set; }
        public virtual DbSet<QuartzCacheSendMail> QuartzCacheSendMails { get; set; }
        public virtual DbSet<Custom_Business_Daily> Custom_Business_Daily { get; set; }
        public virtual DbSet<ProcessFormContent> ProcessFormContents { get; set; }
        public virtual DbSet<OrgNode> OrgNodes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserOrgNode> UserOrgNodes { get; set; }
        public virtual DbSet<PositionUser> PositionUsers { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Custom_Business_WeeklyDaily> Custom_Business_WeeklyDaily { get; set; }
        public virtual DbSet<OrgNodeExtend> OrgNodeExtends { get; set; }
        public virtual DbSet<PositionCategory> PositionCategories { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleUser> RoleUsers { get; set; }
        public virtual DbSet<PositionOrgNode> PositionOrgNodes { get; set; }
        public virtual DbSet<SendErrorLog> SendErrorLogs { get; set; }
        public virtual DbSet<VW_ErrorLog> VW_ErrorLog { get; set; }
        public virtual DbSet<TempSupervision> TempSupervisions { get; set; }
        public virtual DbSet<EmailTransferConfig> EmailTransferConfigs { get; set; }
        public virtual DbSet<QuartzSendMail> QuartzSendMails { get; set; }
        public virtual DbSet<FormAttachment> FormAttachments { get; set; }
        public virtual DbSet<NetworkRole> NetworkRoles { get; set; }
        public virtual DbSet<CommonReportConfig_DisplayArea> CommonReportConfig_DisplayArea { get; set; }
        public virtual DbSet<CommonReportConfig_SearchArea> CommonReportConfig_SearchArea { get; set; }
        public virtual DbSet<Custom_BaseData_ModuleType> Custom_BaseData_ModuleType { get; set; }
        public virtual DbSet<view_ProcinstList> view_ProcinstList { get; set; }
        public virtual DbSet<ProcessLog> ProcessLog { get; set; }
        public virtual DbSet<ProcessFormCancel> ProcessFormCancel { get; set; }
        public virtual DbSet<ProcessActivityParticipantSet> ProcessActivityParticipantSet { get; set; }
        public virtual DbSet<ProcessActivityParticipantSetEntry> ProcessActivityParticipantSetEntry { get; set; }
        public virtual DbSet<ProcessFormCC> ProcessFormCC { get; set; }
        public virtual DbSet<ProcessFormHeader> ProcessFormHeader { get; set; }
        public virtual DbSet<ProcessPrognosis> ProcessPrognosis { get; set; }
        public virtual DbSet<ProcessPrognosisDetail> ProcessPrognosisDetail { get; set; }
        public virtual DbSet<ProcessPrognosisTask> ProcessPrognosisTask { get; set; }
        public virtual DbSet<ProcessFormApprovalDraft> ProcessFormApprovalDraft { get; set; }
        public virtual DbSet<ProcessFormSigner> ProcessFormSigner { get; set; }
        public virtual DbSet<DBLogEntry> DBLogEntry { get; set; }
        public virtual DbSet<CommonReportPermission> CommonReportPermission { get; set; }
    }
}
