//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_BaseData_ToolSoft
    {
        public int ID { get; set; }
        public string ToolType { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Description { get; set; }
        public string Principal { get; set; }
        public string Number { get; set; }
    }
}
