//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBLogEntry
    {
        public System.Guid Id { get; set; }
        public int Priority { get; set; }
        public string Source { get; set; }
        public string Category { get; set; }
        public string Message { get; set; }
        public System.DateTime OccurTime { get; set; }
        public string Exception { get; set; }
    }
}
