//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgNode
    {
        public System.Guid SysId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> Chart_SysId { get; set; }
        public Nullable<System.Guid> Parent_SysId { get; set; }
    }
}
