//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessFormSigner
    {
        public int ProcessInstId { get; set; }
        public string ActivityName { get; set; }
        public string UserName { get; set; }
        public string SignerName { get; set; }
        public Nullable<System.DateTime> SignerDate { get; set; }
        public Nullable<bool> IsApproval { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    }
}
