//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessLog
    {
        public int ID { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public Nullable<int> ActInstID { get; set; }
        public string SN { get; set; }
        public string ProcessName { get; set; }
        public string ActivityName { get; set; }
        public string OrigUserName { get; set; }
        public string OrigUserAccount { get; set; }
        public string UserName { get; set; }
        public string UserAccount { get; set; }
        public string ProfileID { get; set; }
        public string OpType { get; set; }
        public string ActionName { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string TenantID { get; set; }
    }
}
