//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessFormCC
    {
        public System.Guid SysId { get; set; }
        public int FormId { get; set; }
        public string Originator { get; set; }
        public string OriginatorName { get; set; }
        public string Receiver { get; set; }
        public string ReceiverName { get; set; }
        public string FormViewUrl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> ReceiverStatus { get; set; }
        public string ReviewComment { get; set; }
        public Nullable<System.DateTime> ReceiverDate { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string Comment { get; set; }
    }
}
