//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessFormHeader
    {
        public int FormID { get; set; }
        public string FormSubject { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public string ProcessFolio { get; set; }
        public Nullable<int> Priority { get; set; }
        public string SubmitterAccount { get; set; }
        public string SubmitterDisplayName { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string ApplicantAccount { get; set; }
        public string ApplicantDisplayName { get; set; }
        public string ApplicantTelNo { get; set; }
        public string ApplicantEmail { get; set; }
        public string ApplicantPositionID { get; set; }
        public string ApplicantPositionName { get; set; }
        public string ApplicantOrgNodeID { get; set; }
        public string ApplicantOrgNodeName { get; set; }
        public string SubmitComment { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public string DraftUrl { get; set; }
        public string OutSystemProcessID { get; set; }
    }
}
