//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessActivityParticipantSetEntry
    {
        public int ID { get; set; }
        public Nullable<System.Guid> SetID { get; set; }
        public string EntryType { get; set; }
        public Nullable<System.Guid> EntryID { get; set; }
        public string EntryName { get; set; }
    }
}
