//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessActivityParticipantSet
    {
        public System.Guid SetID { get; set; }
        public string Assigner { get; set; }
        public string AssignerName { get; set; }
        public string Setter { get; set; }
        public string SetterName { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public string ProcessFullName { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public string ActivityName { get; set; }
        public Nullable<bool> IsPeeked { get; set; }
        public Nullable<bool> IsOriginal { get; set; }
        public Nullable<bool> SkipAssigner { get; set; }
        public Nullable<bool> SkipSet { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public string Remark { get; set; }
    }
}
