//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aZaaS.KStar.Web.Models.BasisEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ProcinstList
    {
        public int ProcInstID { get; set; }
        public System.DateTime StartDate { get; set; }
        public byte Status { get; set; }
        public string Originator { get; set; }
        public string Folio { get; set; }
        public int ProcID { get; set; }
        public System.DateTime FinishDate { get; set; }
        public string ActName { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public string Destination { get; set; }
        public Nullable<int> ActID { get; set; }
        public string SN { get; set; }
        public string StartName { get; set; }
        public string FullName { get; set; }
    }
}
